# Generated by Django 5.1.4 on 2026-05-14 16:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=170, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="tienda/categorias/"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "categoría de producto",
                "verbose_name_plural": "categorías de productos",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ClientePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=120)),
                ("apellidos", models.CharField(max_length=120)),
                ("telefono", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("direccion", models.TextField()),
                ("departamento", models.CharField(max_length=120)),
                ("municipio", models.CharField(max_length=120)),
                ("nit", models.CharField(blank=True, max_length=30)),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["apellidos", "nombres"],
            },
        ),
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banco", models.CharField(max_length=140)),
                ("nombre_cuenta", models.CharField(max_length=180)),
                ("numero_cuenta", models.CharField(max_length=80)),
                ("tipo_cuenta", models.CharField(max_length=80)),
                ("moneda", models.CharField(default="GTQ", max_length=20)),
                ("instrucciones", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "cuentas bancarias",
                "ordering": ["orden", "banco"],
            },
        ),
        migrations.CreateModel(
            name="MarcaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=170, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="tienda/marcas/"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "marca de producto",
                "verbose_name_plural": "marcas de productos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_pedido",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "costo_envio",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("recibido", "Recibido"),
                            ("pago_en_revision", "Pago en revisión"),
                            ("pago_confirmado", "Pago confirmado"),
                            ("preparando", "Preparando"),
                            ("enviado", "Enviado"),
                            ("entregado", "Entregado"),
                            ("cancelado", "Cancelado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="pendiente",
                        max_length=30,
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[("transferencia_bancaria", "Transferencia bancaria")],
                        default="transferencia_bancaria",
                        max_length=40,
                    ),
                ),
                (
                    "estado_pago",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("comprobante_recibido", "Comprobante recibido"),
                            ("confirmado", "Confirmado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="pendiente",
                        max_length=30,
                    ),
                ),
                (
                    "comprobante_transferencia",
                    models.FileField(
                        blank=True, null=True, upload_to="tienda/comprobantes/"
                    ),
                ),
                ("banco_origen", models.CharField(blank=True, max_length=120)),
                ("numero_referencia", models.CharField(blank=True, max_length=120)),
                ("fecha_transferencia", models.DateField(blank=True, null=True)),
                ("observaciones_cliente", models.TextField(blank=True)),
                ("observaciones_admin", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="tienda.clientepedido",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_tienda",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=220)),
                ("slug", models.SlugField(blank=True, max_length=240, unique=True)),
                ("descripcion_corta", models.CharField(blank=True, max_length=350)),
                ("descripcion_larga", models.TextField(blank=True)),
                ("codigo_sku", models.CharField(max_length=80, unique=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "precio_oferta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "imagen_principal",
                    models.ImageField(
                        blank=True, null=True, upload_to="tienda/productos/"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("destacado", models.BooleanField(default=False)),
                ("nuevo", models.BooleanField(default=False)),
                ("mostrar_en_catalogo", models.BooleanField(default=True)),
                ("permite_compra", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="tienda.categoriaproducto",
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos",
                        to="tienda.marcaproducto",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="ImagenProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="tienda/productos/galeria/")),
                ("alt", models.CharField(blank=True, max_length=180)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="tienda.producto",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_producto_snapshot", models.CharField(max_length=220)),
                ("codigo_sku_snapshot", models.CharField(max_length=80)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="tienda.pedido",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detalles_pedido",
                        to="tienda.producto",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(
                fields=["codigo_pedido"], name="tienda_pedi_codigo__337638_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(
                fields=["estado", "estado_pago"], name="tienda_pedi_estado_7fb5d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(fields=["slug"], name="tienda_prod_slug_646ce0_idx"),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["codigo_sku"], name="tienda_prod_codigo__893de2_idx"
            ),
        ),
    ]
