# Generated by Django 5.1.4 on 2026-05-14 18:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0003_imagenproducto_galeria_mejoras"),
    ]

    operations = [
        migrations.CreateModel(
            name="UbicacionTienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("direccion", models.TextField()),
                (
                    "departamento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("municipio", models.CharField(blank=True, max_length=100, null=True)),
                ("telefono", models.CharField(blank=True, max_length=30, null=True)),
                ("horario", models.CharField(blank=True, max_length=200, null=True)),
                ("google_maps_url", models.URLField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ubicación de tienda",
                "verbose_name_plural": "ubicaciones de tienda",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="detallepedido",
            name="costo_envio_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="detallepedido",
            name="costo_envio_unitario",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="departamento_entrega",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="direccion_entrega",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="municipio_entrega",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="tipo_entrega",
            field=models.CharField(
                choices=[
                    ("recoger_tienda", "Recoger en tienda"),
                    ("envio_domicilio", "Envío a domicilio"),
                ],
                default="envio_domicilio",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="costo_envio",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Indique el costo de envío de este producto. Si es 0, se considerará envío gratuito para este producto.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="ubicacion_recogida",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos",
                to="tienda.ubicaciontienda",
            ),
        ),
    ]
