# Generated by Django 5.1.4 on 2026-05-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0004_ubicaciontienda_detallepedido_costo_envio_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="correo_confirmacion_enviado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pedido",
            name="fecha_correo_confirmacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clientepedido",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
