# Generated by Django 5.1.4 on 2026-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0005_pedido_correo_confirmacion_enviado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("recibido", "Recibido"),
                    ("pago_en_revision", "Pago en revisión"),
                    ("pago_confirmado", "Pago confirmado"),
                    ("preparando", "Preparando"),
                    ("enviado", "Enviado"),
                    ("entregado", "Entregado"),
                    ("listo_recoger", "Listo para recoger en tienda"),
                    ("cancelado", "Cancelado"),
                    ("rechazado", "Rechazado"),
                ],
                default="pendiente",
                max_length=30,
            ),
        ),
    ]
