# Generated by Django 5.1.4 on 2026-07-23 17:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0007_cliente_detallepedido_precio_costo_unitario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="descuento_tipo",
            field=models.CharField(
                choices=[("fijo", "Fijo"), ("porcentaje", "Porcentaje")],
                default="fijo",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="descuento_valor",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="envio",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="impuesto_porcentaje",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
    ]
