# Generated by Django 5.1.4 on 2026-07-23 18:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0008_venta_descuento_tipo_venta_descuento_valor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CotizacionPOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("enviada", "Enviada"),
                            ("aprobada", "Aprobada"),
                            ("convertida", "Convertida en venta"),
                            ("vencida", "Vencida"),
                            ("anulada", "Anulada"),
                        ],
                        default="borrador",
                        max_length=30,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "descuento_tipo",
                    models.CharField(
                        choices=[("fijo", "Fijo"), ("porcentaje", "Porcentaje")],
                        default="fijo",
                        max_length=20,
                    ),
                ),
                (
                    "descuento_valor",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "impuesto_porcentaje",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "envio",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotizaciones_pos",
                        to="tienda.cliente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotizaciones_pos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venta_convertida",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotizacion_origen",
                        to="tienda.venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "cotización POS",
                "verbose_name_plural": "cotizaciones POS",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="DetalleCotizacionPOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "precio_costo_unitario",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="tienda.cotizacionpos",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_cotizacion_pos",
                        to="tienda.producto",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
